version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6.5-node-browsers
      - image: circleci/postgres:10-alpine-ram
    steps:
      - checkout
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
    working_directory: ~/app
    steps:
      - checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
  deploy:
    machine:
      enabled: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Deploy to Gigalixir
          command: |
            git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP.git
            git push -f gigalixir HEAD:refs/heads/master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
